### Get all courses

GET http://localhost:5055/courses HTTP/1.1

### Register course

PUT http://localhost:5055/courses/register HTTP/1.1
content-type: application/json

{
    "name": "Physics"
}

### Register student

PUT http://localhost:5055/students/register HTTP/1.1
content-type: application/json

{
    "name": "Bob",
    "email": "bob@xdc.com"
}

### Edit student data

POST http://localhost:5055/students/1 HTTP/1.1
content-type: application/json

{
    "name": "Alice2",
    "email": "aa@ssss.com"
}

### Get all students

GET http://localhost:5055/students HTTP/1.1

### Get single student

GET http://localhost:5055/students/1 HTTP/1.1

### Enroll to a course

POST http://localhost:5055/students/enroll HTTP/1.1
content-type: application/json

{
    "studentId": "1",
    "courseId": "2",
    "grade": 2
}